import type { Metadata } from "next";
import { ibmPlexSans } from "@/lib/fonts";
import "./globals.css";
import { ApolloProvider } from "@/lib/ApolloProvider";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.className} antialiased`}
      >
        <ApolloProvider>
          <Header />
          <main className="container mx-auto">
            {children}
          </main>
        </ApolloProvider>
      </body>
    </html>
  );
}
